# .github/workflows/jekyll-gh-pages.yml
name: '[Feat] Jekyll, Github Pages 배포'

on:
  push:
    branches: ["main"] # Change to "master" if your primary branch is master
  # Allows manual triggering from the Actions tab
  workflow_dispatch:

# Set permissions for GITHUB_TOKEN to allow deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment runs at a time
concurrency:
  cancel-in-progress: true
  group: pages

jobs:
  # 1. Build Job: Builds the site using your custom environment
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Use a stable Ruby version compatible with the latest Jekyll
          ruby-version: '3.3' 
          # Runs 'bundle install' and caches installed gems
          bundler-cache: true 
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        # Runs the build command, now able to find the plainwhite theme
        run: bundle exec jekyll build 
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site # Upload the built static files

  # 2. Deployment Job: Pushes the artifact to GitHub Pages
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4